### ISSUE TITLE
Compression Support - Feather V2 Support

### ISSUE THREAD

**Issue by ldsands** [JuliaData/Feather.jl#137]
I'm not sure if you've [seen this](https://ursalabs.org/blog/2020-feather-v2/) yet but Arrow V17 is supporting feather V2 which includes compression support.

I'm putting this here more to put it on your radar I realize support for this will almost certainly take time. I use parquet for all of my data right now but given that all of my data is locally stored, feather V2 would probably be a better fit for what I need it for.

Thanks for all of your work!

**Comment by ExpandingMan** [comment]
Yup, feather V2 is really just the arrow IPC file format.  I'm deep into the process of rewriting Arrow.jl and I can already read and mostly write a sizeable subset of the standard.

Since the new feather is just the arrow IPC format and doesn't require any additional code on top of arrow, we will like deprecate this package as legacy for reading Feather V1.

**Comment by ldsands** [comment]
Sounds great to me! I'll have to start following Arrow.jl. Thanks!
